export default {
  login: "Shailendravv",
  id: 96374723,
  node_id: "U_kgDOBb6Pww",
  avatar_url: "https://avatars.githubusercontent.com/u/96374723?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Shailendravv",
  html_url: "https://github.com/Shailendravv",
  followers_url: "https://api.github.com/users/Shailendravv/followers",
  following_url:
    "https://api.github.com/users/Shailendravv/following{/other_user}",
  gists_url: "https://api.github.com/users/Shailendravv/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Shailendravv/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Shailendravv/subscriptions",
  organizations_url: "https://api.github.com/users/Shailendravv/orgs",
  repos_url: "https://api.github.com/users/Shailendravv/repos",
  events_url: "https://api.github.com/users/Shailendravv/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Shailendravv/received_events",
  type: "User",
  site_admin: false,
  name: "Shailendra Singh Chauhan",
  company: "Shyna Tech Yarns",
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Working as a Front-end developer. I have  knowledge on Javascript, Reactjs,NextJs,TypeScript,CSS,HTML",
  twitter_username: null,
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-12-19T10:55:51Z",
  updated_at: "2023-01-21T17:29:37Z",
};
